version: '3'
services:
  rate_limiting_service:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - MAX_TOKENS=2
      - SECONDS_PER_TOKEN=10
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"